export const SET_TITLE = 'SET_TITLE';
export const SET_NUMBER = 'SET_NUMBER';
export const SET_LOGO = 'SET_LOGO';
export const REMOVE_LOGO = 'REMOVE_LOGO';

export const SET_CONTACT_FROM = 'SET_CONTACT_FROM';
export const SET_CONTACT_BILL_TITLE = 'SET_CONTACT_BILL_TITLE';
export const SET_CONTACT_BILL_VALUE = 'SET_CONTACT_BILL_VALUE';
export const SET_CONTACT_SHIP_TITLE = 'SET_CONTACT_SHIP_TITLE';
export const SET_CONTACT_SHIP_VALUE = 'SET_CONTACT_SHIP_VALUE';

export const SET_DETAILS_DATE_TITLE = 'SET_DETAILS_DATE_TITLE';
export const SET_DETAILS_DATE_VALUE = 'SET_DETAILS_DATE_VALUE';
export const SET_DETAILS_TERMS_TITLE = 'SET_DETAILS_TERMS_TITLE';
export const SET_DETAILS_TERMS_VALUE = 'SET_DETAILS_TERMS_VALUE';
export const SET_DETAILS_DUE_DATE_TITLE = 'SET_DETAILS_DUE_DATE_TITLE';
export const SET_DETAILS_DUE_DATE_VALUE = 'SET_DETAILS_DUE_DATE_VALUE';
export const SET_DETAILS_PO_NUMBER_TITLE = 'SET_DETAILS_PO_NUMBER_TITLE';
export const SET_DETAILS_PO_NUMBER_VALUE = 'SET_DETAILS_PO_NUMBER_VALUE';
