export const SET_TITLE = 'SET_TITLE';
export const SET_NUMBER = 'SET_NUMBER';
export const SET_LOGO = 'SET_LOGO';
export const REMOVE_LOGO = 'REMOVE_LOGO';

export const SET_CONTACT_FROM = 'SET_CONTACT_FROM';
export const SET_CONTACT_BILL_TITLE = 'SET_CONTACT_BILL_TITLE';
export const SET_CONTACT_BILL_VALUE = 'SET_CONTACT_BILL_VALUE';
export const SET_CONTACT_SHIP_TITLE = 'SET_CONTACT_SHIP_TITLE';
export const SET_CONTACT_SHIP_VALUE = 'SET_CONTACT_SHIP_VALUE';
